version: "3.8"

services:
  springboot-app:
    image: springboot-app
    container_name: springboot-app
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - app-network

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/user/Desktop/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
